# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Build Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: britannio/action-install-flutter@v1
        with:
          version: stable
      - name: Get Packages
        run: flutter pub get
      - name: Build Web App
        run: flutter build web
      - name: Uploads artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-app
          path: './build/web/'
          overwrite: true
      - name: Downlads Artifacts
        uses: actions/download-artifact@v4
        with:
          name: flutter-web-app 
          path: './artifacts/'
      - name: Display structure of downloaded files
        run: ls -R
        
        
